### ISSUE TITLE
test program can not be compiled:

### ISSUE THREAD

**Issue by shiftleftplusone** [paeryn/openvg#7]
program can not be compiled:

```
// first OpenVG program
// Anthony Starks (ajstarks@gmail.com)
// Adapted for paeryn's fork by paeryn
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include "VG/openvg.h"
#include "VG/vgu.h"
#include "fontinfo.h"
#include "shapes.h"

int main() {
    int width, height;
    char s[3];

    // Request a window size of 600x360 with top-left at 20,20
    initWindowSize(20, 20, 600, 360);
    init(&width, &height);                  // Graphics initialization

    Start(width, height);                   // Start the picture
    Background(0, 0, 0);                    // Black background
    Fill(44, 77, 232, 1);                   // Big blue marble
    Circle(width / 2, 0, width);            // The "world"

    Fill(255, 255, 255, 1);                 // White text
    TextMid(width / 2, height / 2, "hello, world", SerifTypeface, width / 10);  // Greetings 
    End();                                  // End the picture
    WindowOpacity(128); // Make the window half opacity
                // Can now see what is behind it    
    fgets(s, 2, stdin);                     // look at the pic, end with [RETURN]
    finish();                               // Graphics cleanup
    exit(0);
}


```

```
build:
falatal error:
VG/openvg.h: no such file or directory
#include "VG/openvg.h"

compilation terminated

```

**Comment by paeryn** [comment]
It looks like you haven't told the compiler where the OpenVG header files are.
`gcc -I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads example.c -o example -lshapes`

**Comment by shiftleftplusone** [comment]
I am using these geany settings: how do they look like completed then?

I don't look any more through the millions of parameters needed:

```
compile:
g++ -Wall -pthread -I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads -c "%f" -lshapes -lwiringPi -lrt

build
g++ -Wall -pthread -I/opt/vc/include -I/opt/vc/include/interface/vmcs_host/linux -I/opt/vc/include/interface/vcos/pthreads -o "%e" "%f" -lshapes -L/opt/vc/lib -lOpenVG -lEGL -lwiringPi -lrt

```

it would be very convenient if you could wrap your paths in one of your most important primary header files to be included additionally, automatically!
8-)

**Comment by shiftleftplusone** [comment]
edit:
resolved!

in compile section it was correct,
in build section there was something missing!

thank you!

**Comment by shiftleftplusone** [comment]
how can I execute this program using the file manager?
I can only start it via Geany F5 (sudo "./%e" )

**Comment by paeryn** [comment]
_pre-post edit: you replied saying you'd fixed before I posted_

Re: "it would be very convenient if you could wrap your paths in one of your most important primary header files to be included additionally, automatically."
I can't control where the OpenVG headers are and the compiler switches are all needed to tell the compiler where to find them.

If you need to use sudo to run it then I'd suggest you create a shell script that you use to run it. Create a file in the same directory e.g. runprogram.sh containing the two lines
`#!/bin/sh`
`sudo program`
Replace "program" with the name of your executable. Make this file executable from the command line : **chmod u+x runprogram.sh** or by right clicking on it in the filemanager, choose properties -> permissions -> executable (this might be different on the RPi - I don't run the desktop on mine so can't check).

**Comment by shiftleftplusone** [comment]
thank you, but that's too complicated.
I have thousands of files (sequentially updated versions) in hundreds of subdirs and subsubdirs.

can I execute without the sudo  line in geany?
Just by double click in the file manager?

can I drop that effing sudo at all?

**Comment by shiftleftplusone** [comment]
if I start this program above 
testopenvg.c
from the filemanager
testopenvg [ENTER]
 it shortly flashs up but then immediately terminates again.

**Comment by shiftleftplusone** [comment]
no idea what happend, just made some completely different changes and settings to UART and i2c-0,
and suddenly I can execute the testopenvg program "in the terminal" (nevertheless, not just "execute", but anyway.)

Thank you, issue is resolved!
